Get-ExperimentalFeature

# Expects output:
# 
# Name                                Enabled Source  Description
# ----                                ------- ------  -----------
# PSCommandNotFoundSuggestion         False PSEngine  Recommend… 
# PSLoadAssemblyFromNativeCode        False PSEngine  Expose an API… 
# PSNativeCommandErrorActionPreferen… False PSEngine  Native comman…
# PSSubsystemPluginModel              False PSEngine  A plugin mode…
